version: "3.9"

services:
    resaic:
        container_name: resaic
        image: resaic
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - "./logs:./logs"
        env_file:
            - ./.env.docker
        restart: always
        expose:
            - "${PORT}"
        networks:
            - docker

networks:
    docker:
        external: true
