version: "3.9"

services:
    resaic:
        container_name: resaic
        image: resaic
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
            args:
                ENV: ${NODE_ENV}
        environment:
            DOCKER: "true"
            DATABASE_HOST: "mysql"
        volumes:
            - "./logs:/app/logs"
        expose:
            - "${PORT}"
        networks:
            - docker

networks:
    docker:
        external: true
