version: "3.7"

services:
    resaic:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        container_name: resaic
        volumes:
            - ./app:/user/app/app
            - ./server:/user/app/server
            - /user/app/node_modules
        command: bash -c "cp .docker.env .env && yarn start"
        env_file:
          - ./.docker.env
        restart: always
        build: .
        ports:
            - "${PORT}:${PORT}"
        expose:
            - "${PORT}"
        networks:
            - docker
networks:
    docker:
        external: true
